# Generated by Django 3.0.8 on 2020-07-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=150)),
                ('url', models.CharField(max_length=30)),
                ('start_price', models.IntegerField()),
                ('category', models.CharField(max_length=30)),
            ],
        ),
    ]
