# Generated by Django 3.0.8 on 2020-07-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionitems',
            name='url',
        ),
        migrations.AlterField(
            model_name='auctionitems',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auctionitems',
            name='start_price',
            field=models.DecimalField(decimal_places=2, max_digits=100000),
        ),
    ]
