# Generated by Django 3.0.8 on 2020-07-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auctionitems_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitems',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
