# Generated by Django 3.0.8 on 2020-07-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auctionitems_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitems',
            name='title',
            field=models.CharField(max_length=64),
        ),
    ]
