# Generated by Django 3.0.8 on 2020-07-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20200717_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('item_id', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='auctionitems',
            name='category',
            field=models.CharField(choices=[('ART', 'Art'), ('CAR', 'Cars'), ('CLO', 'Cloths'), ('ELE', 'Electronics'), ('FAS', 'Fashion'), ('MAN', 'Manuscript'), ('TOY', 'Toys')], max_length=3),
        ),
    ]
