# Generated by Django 3.0.8 on 2020-08-02 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20200726_1829'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuctionItems',
            new_name='Listings',
        ),
    ]
