# Generated by Django 3.0.8 on 2020-08-02 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20200802_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='value',
            new_name='amount',
        ),
    ]
