# Generated by Django 3.0.8 on 2020-08-02 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20200802_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='item',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='item',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='user',
            new_name='user_id',
        ),
    ]
