# Generated by Django 3.0.8 on 2020-08-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auto_20200802_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='winner',
        ),
        migrations.AddField(
            model_name='listings',
            name='closed',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='bid',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='comments',
            name='text',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='listings',
            name='start_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
