# Generated by Django 3.0.8 on 2020-08-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_auto_20200802_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
