# Generated by Django 3.0.8 on 2020-09-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_auto_20200802_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='winner',
            field=models.TextField(blank=True, null=True),
        ),
    ]
