# Generated by Django 3.0.8 on 2020-09-20 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_listings_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='category',
            field=models.CharField(choices=[('Art', 'Art'), ('Cars', 'Cars'), ('Cloths', 'Cloths'), ('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Manuscript', 'Manuscript'), ('Toys', 'Toys')], max_length=15),
        ),
    ]
